language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - git submodule --quiet update --init --recursive
  - sudo apt-get install -qq valgrind

install:
  - export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden"
  - phpize
  - ./configure --enable-doctrine-instantiator
  - make
  - sudo make install
  - cd doctrine/instantiator && composer dump-autoload

before_script:
  - ulimit -c unlimited || true

script:
  - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes --leak-check=full phpunit --debug
